/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package leetcode

import ArraysAndHashing.solutionSequence

/*
no more havent used this function
see unit test files
 */
fun main() {
    println(solutionSequence(intArrayOf(100,4,200,1,3,2)))
}
